name: Daily Contribution
on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Modify file and commit multiple times
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          for i in {1..10}; do
            date -u >> activity.txt
            git add activity.txt
            git commit -m "Update activity log $i"
          done
          git push
